apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-http-server
spec:
  selector:
    matchLabels:
      app: python-http1
  replicas: 3
  template:
  metadata:
    labels: 
      app: python-http2
  spec:
    imagePullSecrets:
      - name: DockerHubPass
    containers:
      - name: python-http
        image: 9030319796/python-http-server
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
---

apiVersion: v1 
kind: Service
metadata:
  name: python-http-server-service
spec:
  selector:
    app: python-http1
  ports:
  - port: 8080
    protocol: "TCP"
    targetPort: 8080
  type: NodePort

                