apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      name: nginx-selector
      type: web-selector
  template:
    metadata:
      labels:
        name: nginx-selector
        type: web-selector
    spec:
      containers:
      - name: nginx-pod
        image: nginx:latest
  replicas: 3




---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    name: nginx-selector
    type: web-selector
  ports:
  - port: 8080
    targetPort: 8080

