apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    name: myapp
spec:
  containers:
  - name: python-app
    image: 9030319796/python-http-server
    ports:
     - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
